import user1 from '../../assets/user1.webp';
import user2 from '../../assets/user2.webp';
import user3 from '../../assets/user3.webp';
import user4 from '../../assets/user4.webp';
import user5 from '../../assets/user5.webp';
export const transactionData = [
  {
    key: '1',
    customer: 'Flyod Johntosan',
    email: 'johntosan@gmail.com',
    status: 'Success',
    date: 'Nov 02, 2022',
    invoice: '$100,00',
    amount: 10000,
    people: [
      { src: user2, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user4, backgroundColor: '#ffc6b7', border: '2px solid white' },
    ],

    image: user4,
  },
  {
    key: '2',
    customer: 'Rachel Green',
    email: 'rachel@gmail.com',
    status: 'Pending',
    date: 'Nov 15, 2022',
    invoice: '$80,00',

    amount: 8000,
    image: user1,
    people: [
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user4, backgroundColor: '#ffc6b7', border: '2px solid white' },
      { src: user5, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user1, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user4, backgroundColor: '#ffc6b7', border: '2px solid white' },
    ],
  },
  {
    key: '3',
    customer: 'Monica Palmer',
    email: 'monica@gmail.com',
    status: 'Pending',
    date: 'Aug 02, 2022',
    invoice: '$110,00',

    amount: 11000,
    people: [
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user4, backgroundColor: '#ffc6b7', border: '2px solid white' },
      { src: user5, backgroundColor: '#f7c236', border: '2px solid white' },
    ],
    image: user2,
  },
  {
    key: '4',
    customer: 'Rachel Zain',
    email: 'zain racheln@gmail.com',
    status: 'Success',
    date: 'Aug 22, 2022',
    invoice: '$90,00',
    amount: 9000,
    people: [
      { src: user4, backgroundColor: '#ffc6b7', border: '2px solid white' },
      { src: user5, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user1, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
    ],
    image: user3,
  },
  {
    key: '5',
    customer: 'Flyod Johntosan',
    email: 'johntosan@gmail.com',
    status: 'Success',
    date: 'Sept 02, 2022',
    invoice: '$100,00',
    amount: 10000,
    people: [
      { src: user2, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user1, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
    ],
    image: user4,
  },
  {
    key: '6',
    customer: 'Chandler Bing',
    email: 'chandler@gmail.com',
    status: 'Success',
    date: 'Sept 15, 2022',
    invoice: '$100,00',
    amount: 8000,
    people: [
      { src: user5, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user1, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
    ],
    image: user5,
  },
  {
    key: '7',
    customer: 'Monica Palmer',
    email: 'monica@gmail.com',
    status: 'Pending',
    date: 'Oct 02, 2022',
    invoice: '$120,00',
    amount: 11000,
    people: [
      { src: user4, backgroundColor: '#ffc6b7', border: '2px solid white' },
      { src: user5, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user1, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
    ],
    image: user2,
  },
  {
    key: '8',
    customer: 'Rachel Green',
    email: 'rachel@gmail.com',
    status: 'Success',
    date: 'Oct 22, 2022',
    invoice: '$70,00',
    amount: 9000,
    people: [
      { src: user2, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
      { src: user4, backgroundColor: '#ffc6b7', border: '2px solid white' },
      { src: user5, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user1, backgroundColor: '#f7c236', border: '2px solid white' },
      { src: user3, backgroundColor: '#c7f1f7', border: '2px solid white' },
    ],
    image: user1,
  },
];
